# Generated by Django 3.2.23 on 2023-12-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('des', models.TextField()),
                ('petid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pets.pet')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.user')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
